# Generated by Django 5.2.16 on 2026-07-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('quando_pretende', models.CharField(blank=True, max_length=60)),
                ('utm_source', models.CharField(blank=True, max_length=60)),
                ('utm_campaign', models.CharField(blank=True, max_length=60)),
                ('pagina_origem', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='novo', max_length=20)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
