# Generated by Django 5.2.16 on 2026-07-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='nutridora_ultimo_toque',
            field=models.CharField(blank=True, choices=[('t1', 'T+1'), ('t3', 'T+3'), ('t7', 'T+7')], max_length=2),
        ),
    ]
