# Generated by Django 5.2.16 on 2026-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_nutridora_ultimo_toque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='nome',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
