# Generated by Django 5.2.16 on 2026-07-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conviteavaliacao',
            name='escopo',
            field=models.CharField(choices=[('turma', 'Turma toda (link compartilhado)'), ('individual', 'Pessoa específica')], default='turma', max_length=10),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='convite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avaliacoes.conviteavaliacao'),
        ),
    ]
