# Generated by Django 5.2.16 on 2026-07-18 01:41

import apps.midia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0004_turma_consentimento_midia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120)),
                ('legenda', models.TextField(blank=True)),
                ('canal', models.CharField(default='instagram', max_length=30)),
                ('modo', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pronta', 'Pronta'), ('publicada', 'Publicada')], default='rascunho', max_length=10)),
                ('url_publicada', models.URLField(blank=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='cursos.turma')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MidiaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo'), ('arte', 'Arte')], max_length=10)),
                ('arquivo', models.FileField(upload_to=apps.midia.models.caminho_midia)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='turmas/thumbs/')),
                ('legenda', models.CharField(blank=True, max_length=160)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('aula_data', models.DateField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('instrutor', 'Instrutor'), ('studio', 'Studio')], default='instrutor', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='cursos.turma')),
                ('postagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artes', to='midia.postagem')),
            ],
            options={
                'verbose_name': 'Mídia da turma',
                'verbose_name_plural': 'Mídias da turma',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
