# Generated by Django 5.2.16 on 2026-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='agendada_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
