# Generated by Django 5.2.16 on 2026-07-15 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_origem', models.CharField(choices=[('template', 'Template'), ('editado', 'Editado')], default='template', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=12)),
                ('titulo_venda', models.CharField(max_length=160)),
                ('titulo_destaque', models.CharField(blank=True, max_length=60)),
                ('subtitulo', models.TextField()),
                ('imagem_hero', models.ImageField(blank=True, upload_to='cursos/hero/')),
                ('carga_horaria', models.PositiveIntegerField(help_text='em horas')),
                ('formato', models.CharField(default='Presencial', max_length=80)),
                ('dias_e_horario_padrao', models.CharField(blank=True, max_length=80)),
                ('publico_alvo', models.TextField(blank=True)),
                ('requisitos', models.TextField(blank=True, default='Nenhum — formação do zero')),
                ('texto_pratica', models.TextField(blank=True)),
                ('imagem_pratica', models.ImageField(blank=True, upload_to='cursos/pratica/')),
                ('texto_carreira', models.TextField(blank=True)),
                ('imagem_carreira', models.ImageField(blank=True, upload_to='cursos/carreira/')),
                ('itens_inclusos', models.JSONField(blank=True, default=list)),
                ('saidas_profissionais', models.JSONField(blank=True, default=list)),
                ('seo_titulo', models.CharField(blank=True, max_length=70)),
                ('seo_descricao', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_origem', models.CharField(choices=[('template', 'Template'), ('editado', 'Editado')], default='template', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('icone', models.CharField(blank=True, max_length=30)),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_origem', models.CharField(choices=[('template', 'Template'), ('editado', 'Editado')], default='template', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('registro', models.CharField(blank=True, max_length=60)),
                ('especializacao', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='instrutores/')),
                ('cursos', models.ManyToManyField(blank=True, related_name='instrutores', to='cursos.curso')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_origem', models.CharField(choices=[('template', 'Template'), ('editado', 'Editado')], default='template', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('pergunta', models.CharField(max_length=160)),
                ('resposta', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_origem', models.CharField(choices=[('template', 'Template'), ('editado', 'Editado')], default='template', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('inscricoes', 'Inscrições abertas'), ('lotada', 'Lotada'), ('em_andamento', 'Em andamento'), ('encerrada', 'Encerrada')], default='rascunho', max_length=14)),
                ('inicio_aulas', models.DateField(blank=True, null=True)),
                ('exibir_inicio', models.BooleanField(default=False)),
                ('dias_e_horario', models.CharField(blank=True, max_length=80)),
                ('capacidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vagas_restantes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exibir_vagas', models.BooleanField(default=False)),
                ('exibir_countdown', models.BooleanField(default=False)),
                ('countdown_ate', models.DateTimeField(blank=True, null=True)),
                ('rotulo_countdown', models.CharField(default='Condição de matrícula antecipada encerra em', max_length=80)),
                ('preco_cheio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preco_avista', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parcelas_qtd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parcela_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('exibir_preco', models.BooleanField(default=False)),
                ('obs_pagamento', models.CharField(blank=True, max_length=160)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos.curso')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.instrutor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='AnotacaoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='cursos.turma')),
            ],
            options={
                'verbose_name': 'Anotação de turma',
                'verbose_name_plural': 'Anotações de turma',
            },
        ),
    ]
