# Generated by Django 5.2.16 on 2026-07-16 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_origem', models.CharField(choices=[('template', 'Template'), ('editado', 'Editado')], default='template', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('imagem', models.ImageField(upload_to='cursos/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=120)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Foto do curso',
                'verbose_name_plural': 'Fotos do curso',
                'ordering': ['ordem'],
            },
        ),
    ]
