# Generated by Django 5.2.16 on 2026-07-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_fotocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotocurso',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cursos.turma'),
        ),
    ]
