# Generated by Django 5.2.16 on 2026-07-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_fotocurso_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='consentimento_midia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='consentimento_midia_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
