# Generated by Django 5.2.16 on 2026-07-23 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educacional', '0005_matricula_pura_aluno_obrigatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox (testes)'), ('producao', 'Produção (dinheiro real)')], max_length=10, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=1000)),
                ('webhook_token', models.CharField(blank=True, max_length=1000)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração Asaas',
                'verbose_name_plural': 'Configurações Asaas',
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão'), ('UNDEFINED', 'Aluno escolhe')], max_length=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('estornada', 'Estornada')], default='pendente', max_length=10)),
                ('vencimento', models.DateField()),
                ('link_pagamento', models.URLField()),
                ('asaas_id', models.CharField(max_length=40, unique=True)),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox (testes)'), ('producao', 'Produção (dinheiro real)')], max_length=10)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='educacional.matricula')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoWebhookAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.CharField(blank=True, max_length=60)),
                ('payload', models.JSONField()),
                ('status_processamento', models.CharField(choices=[('processado', 'Processado'), ('ignorado', 'Ignorado — cobrança não encontrada')], max_length=12)),
                ('cobranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_webhook', to='financeiro.cobranca')),
            ],
            options={
                'verbose_name': 'Evento de webhook Asaas',
                'verbose_name_plural': 'Eventos de webhook Asaas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
