# Generated by Django 5.2.16 on 2026-07-24 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_lead_nutridora_ultimo_toque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('numero', models.CharField(db_index=True, max_length=20)),
                ('nome_contato', models.CharField(blank=True, max_length=120)),
                ('papel', models.CharField(blank=True, max_length=20)),
                ('agente', models.CharField(blank=True, help_text='Qual agente atendeu: sdr, operadora, nutridora, radar.', max_length=20)),
                ('ultima_atividade_em', models.DateTimeField(db_index=True)),
                ('escalada', models.BooleanField(default=False, help_text='Houve handoff pro humano nesta conversa.')),
                ('desfecho', models.CharField(blank=True, choices=[('', 'Sem desfecho'), ('lead_registrado', 'Lead registrado'), ('handoff', 'Passou pro humano'), ('matricula', 'Matrícula'), ('cobranca', 'Cobrança gerada')], default='', max_length=20)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-ultima_atividade_em'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('contato', 'Contato'), ('agente', 'Agente'), ('sistema', 'Sistema')], max_length=10)),
                ('texto', models.TextField(blank=True)),
                ('agente', models.CharField(blank=True, max_length=20)),
                ('ferramentas', models.JSONField(blank=True, default=list)),
                ('execucao_n8n', models.CharField(blank=True, max_length=40)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='conversas.conversa')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['numero', '-ultima_atividade_em'], name='conversas_c_numero_deaf76_idx'),
        ),
    ]
