# Generated by Django 5.2.16 on 2026-07-16 00:19

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _matricula_expiracao_padrao_historico():
    # Cópia congelada de `matricula_expiracao_padrao` (removida do models.py
    # na spec 014, junto com o campo `expira_em`) — migrations históricas
    # não podem depender de símbolos que deixaram de existir no código
    # atual; o valor em si não importa mais (o campo é dropado numa
    # migration posterior), só precisa ser importável.
    return timezone.now() + datetime.timedelta(days=90)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('origem_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('convidado', 'Convidado (aguardando preenchimento)'), ('ativa', 'Ativa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='convidado', max_length=12)),
                ('codigo_carteirinha', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('validade_carteirinha_meses', models.PositiveSmallIntegerField(default=24)),
                ('validade_carteirinha', models.DateField(blank=True, editable=False, null=True)),
                ('valor_fechado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30)),
                ('expira_em', models.DateTimeField(default=_matricula_expiracao_padrao_historico)),
                ('preenchida_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='educacional.aluno')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='cursos.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
