# Generated by Django 5.2.16 on 2026-07-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='escopo',
            field=models.CharField(choices=[('turma', 'Turma toda (link compartilhado)'), ('individual', 'Pessoa específica')], default='turma', max_length=10),
        ),
    ]
