# Generated by Django 5.2.16 on 2026-07-18 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvedorIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('provedor', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('credencial', models.CharField(blank=True, max_length=1000)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('testado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Provedor de IA',
                'verbose_name_plural': 'Provedores de IA',
                'ordering': ['tipo', '-ativo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('capacidade', models.CharField(max_length=40)),
                ('contexto_resumo', models.CharField(blank=True, max_length=255)),
                ('tokens_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_saida', models.PositiveIntegerField(blank=True, null=True)),
                ('duracao_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('erro', 'Erro')], max_length=10)),
                ('erro', models.TextField(blank=True)),
                ('agente', models.CharField(blank=True, max_length=60)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_ia', to=settings.AUTH_USER_MODEL)),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='ia.provedoria')),
            ],
            options={
                'verbose_name': 'Execução de IA',
                'verbose_name_plural': 'Execuções de IA',
                'ordering': ['-criado_em'],
            },
        ),
    ]
