# Generated by Django 5.2.16 on 2026-07-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedoria',
            name='provedor',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini')], max_length=20),
        ),
    ]
