# Generated by Django 5.2.16 on 2026-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_origem', models.CharField(choices=[('template', 'Template'), ('editado', 'Editado')], default='template', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('whatsapp_principal', models.CharField(default='5521964946079', max_length=20)),
                ('instagram', models.CharField(default='@magma_curso', max_length=60)),
                ('email', models.EmailField(default='curso.magma21@gmail.com', max_length=254)),
                ('endereco', models.TextField(default='Rua Nossa Senhora de Fátima, 495 — Olinda, Nilópolis/RJ')),
                ('nota_google', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('total_alunos_formados', models.PositiveIntegerField(blank=True, null=True)),
                ('exibir_nota_google', models.BooleanField(default=False)),
                ('exibir_total_formados', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configuração do site',
            },
        ),
    ]
