# Generated by Django 5.2.16 on 2026-07-18 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('escopos', models.JSONField(blank=True, default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Token de agente',
                'verbose_name_plural': 'Tokens de agente',
            },
        ),
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acao', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('resultado_resumo', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('erro', 'Erro')], max_length=6)),
                ('erro', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.tokenagente')),
            ],
            options={
                'verbose_name': 'Log de ação',
                'verbose_name_plural': 'Logs de ações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
