# Generated by Django 5.2.16 on 2026-07-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_tokenagente_logacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenagente',
            name='escopos',
            field=models.JSONField(blank=True, default=list, help_text='Lista JSON de escopos liberados pra esse agente, ex.: ["*"] (tudo) ou ["avaliacoes:gerar_link_avaliacao", "midia:*"]. Ver GET /api/acoes/ pro nome do escopo de cada ação.'),
        ),
        migrations.AlterField(
            model_name='tokenagente',
            name='nome',
            field=models.CharField(help_text='Identifica o agente, ex.: agente-n8n.', max_length=60, unique=True),
        ),
    ]
