# Generated by Django 5.2.16 on 2026-07-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_alter_tokenagente_escopos_alter_tokenagente_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoEscalado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(help_text='Só dígitos com DDI, mesmo formato de Usuario.whatsapp/Lead.whatsapp.', max_length=20, unique=True)),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contato escalado',
                'verbose_name_plural': 'Contatos escalados',
            },
        ),
    ]
