# Generated by Django 5.2.16 on 2026-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_contatoescalado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='whatsapp_principal',
            field=models.CharField(default='5521979767821', max_length=20),
        ),
    ]
