# Generated by Django 5.2.16 on 2026-07-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_alter_configuracaosite_whatsapp_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='conversas_retencao_dias',
            field=models.PositiveIntegerField(default=15, help_text='Por quantos dias guardar as conversas do agente com os contatos. 0 = nunca apagar.'),
        ),
    ]
