# Generated by Django 5.2.16 on 2026-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_configuracaosite_conversas_retencao_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatoescalado',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Contato escalado', 'verbose_name_plural': 'Contatos escalados'},
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='handoff_expira_horas',
            field=models.PositiveIntegerField(default=24, help_text='Depois de quantas horas um contato escalado volta a ser atendido pela MAG, se ninguém resolver. 0 = nunca expira.'),
        ),
        migrations.AddField(
            model_name='contatoescalado',
            name='expira_em',
            field=models.DateTimeField(blank=True, help_text='Passado este momento a MAG volta a atender sozinha, mesmo sem ninguém resolver. Vazio = nunca expira.', null=True),
        ),
        migrations.AddField(
            model_name='contatoescalado',
            name='resolvido_em',
            field=models.DateTimeField(blank=True, help_text='Quando a equipe devolveu o contato pro atendimento automático.', null=True),
        ),
        migrations.AlterField(
            model_name='contatoescalado',
            name='numero',
            field=models.CharField(db_index=True, help_text='Só dígitos com DDI, mesmo formato de Usuario.whatsapp/Lead.whatsapp.', max_length=20),
        ),
    ]
