# Generated by Django 5.2.16 on 2026-07-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_alter_contatoescalado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='nutridora_silencio_dias',
            field=models.PositiveIntegerField(default=2, help_text='Quantos dias sem falar com a MAG um lead precisa ficar antes de receber toque automático da Nutridora. 0 = não checar conversa (pode tocar alguém no meio do papo).'),
        ),
    ]
